title: TELOS Collaboration
description: Theoretical Explorations on the Lattice with Orthogonal and Symplectic groups

url: https://telos-collaboration.github.io/
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, jekyll-spaceship]
paginate: 5

navigation:
    - title: About
      url: /index.html
    - title: News
      url: /news
    - title: Members
      url: /members
    - title: Publications
      url: /publications
    - title: Open Science
      url: /openscience
    - title: Opportunities
      url: /opportunities
    - title: Acknowledgements
      url: /support

social:
    github: telos-collaboration
